# Generated by Django 4.2.15 on 2024-08-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
